version: 2
jobs:
  build:

    branches:
      only:
       - master
   
    working_directory: ~/jacs-storage

    docker:
      - image: circleci/openjdk:8u171-jdk

    environment:
      TERM: dumb

    steps:

      - checkout

      - restore_cache:
          keys: 
            - jacs-storage-c1-{{ checksum "build.gradle" }}
            - jacs-storage-c1-
      
      - run: ./gradlew --no-daemon dependencies
      
      - save_cache:
          key: jacs-storage-c1-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - run: ./gradlew --no-daemon installDist test

      - store_test_results:
          path: jacsstorage-agentweb/build/test-results/test

      - store_test_results:
          path: jacsstorage-api/build/test-results/test

      - store_test_results:
          path: jacsstorage-core/build/test-results/test

      - store_test_results:
          path: jacsstorage-masterweb/build/test-results/test

      - store_test_results:
          paths: jacsstorage-services/build/test-results/test
